name: 'Typescript action: generate indexes'
description: 'Generate indexes.ts for a typescript project'
branding:
  icon: activity
  color: blue
inputs:
  folder:
    description: The folder path to start at
    required: true,
  excludes:
    description: The patterns to use to exclude files and folders
    required: false,
    default: ""
  export_sub_index:
    description: Whenever or not a index.ts file should be specially exported
    required: false,
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
